### ISSUE TITLE
Inject User Agent String

### ISSUE THREAD

**Issue by codealfa** [unicframework/user-agent#1]
Would love an option to be able to supply a user agent string to be parsed (probably in the constructor) rather than always hard-coded to server response.

Otherwise seems perfect for my use. Thank you.

**Comment by rajkumardusad** [comment]
> Would love an option to be able to supply a user agent string to be parsed (probably in the constructor) rather than always hard-coded to server response.
> 
> Otherwise seems perfect for my use. Thank you.

Hey @codealfa nice idea, we will add this in our upcoming version. thanks for your valuable suggestion.

**Comment by rajkumardusad** [comment]
> Would love an option to be able to supply a user agent string to be parsed (probably in the constructor) rather than always hard-coded to server response.
> 
> Otherwise seems perfect for my use. Thank you.

Hey @codealfa our new version is released, now you can parse custom user agent string.

**Comment by codealfa** [comment]
Perfect! Thank you!
